language: android
jdk: oraclejdk8
addons:
  apt:
    packages:
    # Updates JDK 8 to the latest available.
      - oracle-java8-installer
sudo: false
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
licenses:
    - 'android-sdk-license-.+'
before_script:
  # Update app version
  - .travis_buildscript/version_upgrade.sh
script: ./gradlew assemble
notifications:
    email: false
    slack: post2shyam:1szenHzyMD0Yk5PISyepu4Fw
after_success:
    # Upload to app center
    - .travis_buildscript/publish_apk.sh